images/urls.py
from django.urls import path
# import views
from .views import HomeView,CreatePoductView, ProductDetailView,AddProductImages
    #AddPoductView, ProductDetailView, AddProductImagesView

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('addproduct', CreatePoductView.as_view(), name="addproduct"),
    path('productdetail/<int:pk>/', ProductDetailView.as_view(), name="productdetail"),
    path('addimages/<int:pk>/', AddProductImages.as_view(), name="addimages"),
]

productimages/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('images.urls'))
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=70)
    banner = models.ImageField(upload_to="product/banner")

    def __str__(self):
        return self.title


class Images(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    images = models.ImageField(upload_to="product/images")

images/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter title',
            }),
            'display_image': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'placeholder': 'Select banner image',
            }),
        }

images/views.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, CreateView
from .forms import ProductForm
from django.urls import reverse_lazy
from .models import Images, Product


# Create your views here.
class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['productlist'] = Product.objects.all()
        return context


# add product
class CreatePoductView(CreateView):
    template_name = "add_product.html"
    form_class = ProductForm
    success_url = reverse_lazy('home')


# product detail
class ProductDetailView(TemplateView):
    template_name = "productdetails.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['productobj'] = Product.objects.get(id=self.kwargs['pk'])
        return context
#
#
# # add immages of product
class AddProductImages(TemplateView):
    template_name = "add_images.html"

    def post(self,  *args, **kwargs):
        try:
            images = self.request.FILES.getlist('images')
            product = Product.objects.get(id=self.kwargs['pk'])
            for image in images:
                product_images = Images.objects.create(
                    product=product,
                    images=image
                )
            return redirect('home')
        except Exception as e:
            print(e)

templates/add_images.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container my-4">
    <h1>Add images</h1>
    <br />
    <hr />
    <form action="" method="POST" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        <label>Images</label>
        <br />
        <input class="form-control" multiple id="" type="file" name="images" />
        <br />
        <button class="btn btn-primary my-3" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

templates/add_product.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container my-5">
    <h1>Add product</h1>
    <br />
    <hr />
    <form method="POST" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{form.title}}
        <br />
        {{form.banner}}
        <br />
        <button class="btn btn-primary my-3" type="submit">Submit</button>
        <br />
    </form>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>Blog!</title>
</head>

<body>
    {% block body %}{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container my-4">
    <br />
    <h1>Upload multiple images in django</h1>
    <br />
    <a href="{% url 'addproduct' %}" class="btn btn-success btn-sm">Create product</a>
    <br />
    <hr />
    <div class="row">
        {% for product in productlist %}
        <div class="card m-5" style="width: 23rem;">
            <img src="{{product.banner.url}}" class="card-img-top" alt="..." style="width: 350px; height: 300px;">
            <div class="card-body">
                <h5 class="card-title">{{product.title}}</h5>
                <a href="{% url 'productdetail' product.id %}" class="btn btn-primary btn-sm">Detail</a>
                <a href="{% url 'addimages' product.id %}" class="btn btn-secondary btn-sm">Add images</a>
            </div>

        </div>
        {% empty %}
                    <p>No product yet</p>

        {% endfor %}
    </div>
</div>
{% endblock %}

templates/productdetails.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="container my-4">
    <h2>Product detail</h2>
    <br />
    <hr />
    <h4>{{productobj.title}}</h4>
    <br />
    {% for pimage in productobj.images_set.all %}
    <img src="{{pimage.images.url}}" class="card-img-top" alt="..." style="width: 200px; height: 200px;">
    {% empty %}
    <p>No images yet </p>
    {% endfor %}
    
</div>
{% endblock %}